@startuml class
abstract class ProgramBase {
    + {abstract} Start(args: string[], length: int)
}

class Program {
    - argumentProcessor: ArgumentProcessorBase
}

abstract class ArgumentValidatorBase {
    + {abstract} Validate(args: string[], length: int): boolean
}

class ArgumentValidator {
}

abstract class ArgumentProcessorBase {
    + {abstract} Process(args: string[], length: int)
}

class ArgumentProcessor {
    - argumentValidator: ArgumentValidatorBase
    - passwordGenerator: PasswordGeneratorBase
    - terminal: TerminalBase
}

abstract class TerminalBase {
    + {abstract} Show(message: string)
}

class Terminal {
}

abstract class PasswordGeneratorBase {
    + {abstract} Generate(): string
}

class PasswordGenerator {
}

ArgumentValidatorBase <|-- ArgumentValidator
ArgumentProcessorBase <|-- ArgumentProcessor
TerminalBase <|-- Terminal
PasswordGeneratorBase <|-- PasswordGenerator
ProgramBase <|-- Program

Program *--l ArgumentProcessorBase

ArgumentProcessor *--l ArgumentValidatorBase
ArgumentProcessor *--d PasswordGeneratorBase
ArgumentProcessor *--r TerminalBase
@enduml